spring:
  application:
    name: nlw-planner

  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    url: jdbc:h2:mem:planner
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  jpa:
    open-in-view: false
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console